db:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
  ports:
    - "3306:3306"

web:
  build: .
  command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
  volumes:
    - .:/community_board
  ports:
    - "3000:3000"
  links:
    - db